apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kubeflow
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  # echo -n BASE64_AWS_ACCESS_KEY_ID | base64
  # echo -n BASE64_AWS_SECRET_ACCESS_KEY | base64